### ISSUE TITLE
Command Request: Issues

### ISSUE THREAD

**Issue by PyGamer0** [Vyxal/VyxalBotSE#19]
Issues will take one argument (Vyxal by default), and show the 3 most recently opened issues for the repo.

Issue will be another commad which will take 2 arguments (Vyxal will be default for the first argument); first argument is the repo name and the second is issue number. It will show the issue in more detail.

## Example
```
!!/issues
#342 Commands not working
#664 Vectorisation notworking on negative numbers

!!/issue #86
+-----------------+
| This command..  |
+-----------------+
| This command    |
| Doesnt work..   |
+-----------------+
```

**Comment by hyper-neutrino** [comment]
Declined as I do not believe this is worth my time or that it actually adds anything, when you could just open GitHub.
