### ISSUE TITLE
Don't report review comments on PRs

### ISSUE THREAD

**Issue by ysthakur** [Vyxal/VyxalBotSE#31]
When a PR's being reviewed by someone, there should only be one message in chat about the review, not a different message for each comment within. For example, pxeger made 15 comments, and [15 messages](https://chat.stackexchange.com/transcript/message/58770333#58770333) were posted by VyxalBot. This isn't helpful at all. There should only be a link to the [first comment](https://github.com/Vyxal/Vyxal/pull/206#discussion_r680509590) or to a [comment](https://github.com/Vyxal/Vyxal/pull/206#pullrequestreview-719665991) for the entire review if it exists.

I understand that GitHub's webhooks are hard to do stuff with, but I'm just putting this out here for the future.

**Comment by hyper-neutrino** [comment]
completed
